<?xml version="1.0"?>
<robot name="box" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="box_len_x" value="0.156" />
<xacro:property name="box_len_y" value="0.257" />
<xacro:property name="box_len_z" value="0.0794" />

<xacro:property name="box_origin_from_corner" value="${box_len_x/2} ${box_len_y/2} ${box_len_z/2}" />

<link name="box_base_link">

</link>

<joint name="box_center_joint" type="fixed">
  <parent link="box_base_link"/>
  <child link="box_center_link"/>
  <origin rpy="0 0 0" xyz="${box_origin_from_corner}"/>
</joint>
<link name="box_center_link">
  <visual>
    <origin rpy="0 0 0" xyz="-${box_len_x/2} -${box_len_y/2} -${box_len_z/2}"/>
    <geometry>
      <mesh filename="package://box_description/meshes/box.dae" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white">
      <color rgba="1 1 1 1"/>
    </material>
  </visual>
</link>

<!-- Box Corners -->

<joint name="box_corner_1_joint" type="fixed">
  <parent link="box_center_link"/>
  <child link="box_corner_1"/>
  <origin rpy="0 0 0" xyz="-${box_len_x/2} -${box_len_y/2} -${box_len_z/2}"/>
</joint>

<link name="box_corner_1">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <sphere radius="0.01"/>
    </geometry>
  </visual>
</link>

<joint name="box_corner_2_joint" type="fixed">
  <parent link="box_center_link"/>
  <child link="box_corner_2"/>
  <origin rpy="0 0 0" xyz="${-1 * box_len_x/2} ${box_len_y/2} -${box_len_z/2}"/>
</joint>

<link name="box_corner_2">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <sphere radius="0.01"/>
    </geometry>
  </visual>
</link>

<joint name="box_corner_3_joint" type="fixed">
  <parent link="box_center_link"/>
  <child link="box_corner_3"/>
  <origin rpy="0 0 0" xyz="${box_len_x/2} ${box_len_y/2} -${box_len_z/2}"/>
</joint>

<link name="box_corner_3">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <sphere radius="0.01"/>
    </geometry>
  </visual>
</link>

<joint name="box_corner_4_joint" type="fixed">
  <parent link="box_center_link"/>
  <child link="box_corner_4"/>
  <origin rpy="0 0 0" xyz="${box_len_x/2} ${-1 * box_len_y/2} -${box_len_z/2}"/>
</joint>

<link name="box_corner_4">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <sphere radius="0.01"/>
    </geometry>
  </visual>
</link>

<!-- Buttons -->

<joint name="box_button_blue_joint" type="fixed">
  <parent link="box_corner_2"/>
  <child link="box_button_blue"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.03405 -0.03225 ${box_len_z}"/>
</joint>
<link name="box_button_blue">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 ${0.0041/2}"/>
    <geometry>
      <cylinder radius="0.00525" length="0.0041"/>
    </geometry>
    <material name="blue">
      <color rgba="0 0 1 1"/>
    </material>
  </visual>
</link>

<joint name="box_button_red_joint" type="fixed">
  <parent link="box_corner_2"/>
  <child link="box_button_red"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.04805 -0.03225 ${box_len_z}"/>
</joint>
<link name="box_button_red">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 ${0.0041/2}"/>
    <geometry>
      <cylinder radius="0.00525" length="0.0041"/>
    </geometry>
    <material name="red">
      <color rgba="1 0 0 1"/>
    </material>
  </visual>
</link>

<!-- Slider -->

<joint name="box_slider_joint" type="fixed">
  <parent link="box_corner_3"/>
  <child link="box_slider"/>
  <origin rpy="0 ${pi} ${pi}" xyz="-0.0425 -0.0675 ${box_len_z}"/>
</joint>
<link name="box_slider">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0.005"/>
    <geometry>
      <box size="0.007 0.005796 0.01"/>
    </geometry>
  </visual>
</link>

<!-- Sockets -->

<joint name="box_socket_red_joint" type="fixed">
  <parent link="box_corner_2"/>
  <child link="box_socket_red"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.0589 -0.0895 ${box_len_z}"/>
</joint>
<link name="box_socket_red">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0.001"/>
    <geometry>
      <cylinder radius="0.007" length="0.002"/>
    </geometry>
    <material name="red">
      <color rgba="1 0 0 1"/>
    </material>
  </visual>
</link>

<joint name="box_socket_black_joint" type="fixed">
  <parent link="box_corner_2"/>
  <child link="box_socket_black"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.034 -0.0895 ${box_len_z}"/>
</joint>
<link name="box_socket_black">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0.001"/>
    <geometry>
      <cylinder radius="0.007" length="0.002"/>
    </geometry>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
  </visual>
</link>

<joint name="box_socket_grey_joint" type="fixed">
  <parent link="box_corner_4"/>
  <child link="box_socket_grey"/>
  <origin rpy="0 -${pi/2} 0" xyz=" -0.0482 0.0265 0.0963"/>
</joint>
<link name="box_socket_grey">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 -0.001"/>
    <geometry>
      <cylinder radius="0.007" length="0.002"/>
    </geometry>
    <material name="grey">
      <color rgba="0.5 0.5 0.5 1"/>
    </material>
  </visual>
</link>

<!-- Measuring Points -->

<joint name="box_measuring_point_1_joint" type="fixed">
  <parent link="box_base_link"/>
  <child link="box_measuring_point_1"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.0904 0.0836 0.072"/>
</joint>
<link name="box_measuring_point_1">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0.01 0.01 0.1"/>
    </geometry>
  </visual>
</link>

<joint name="box_measuring_point_2_joint" type="fixed">
  <parent link="box_base_link"/>
  <child link="box_measuring_point_2"/>
  <origin rpy="0 ${pi} ${pi}" xyz="0.0528 0.0836 0.061"/>
</joint>
<link name="box_measuring_point_2">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0.01 0.01 0.1"/>
    </geometry>
  </visual>
</link>

<joint name="box_measuring_point_3_joint" type="fixed">
  <parent link="box_base_link"/>
  <child link="box_measuring_point_3"/>
  <origin rpy="0 ${pi} ${pi} " xyz="0.0394 0.0836 0.05"/>
</joint>
<link name="box_measuring_point_3">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <box size="0.01 0.01 0.1"/>
    </geometry>
  </visual>
</link>



<!-- Display -->
<joint name="box_display_joint" type="fixed">
  <parent link="box_corner_3"/>
  <child link="box_display"/>
  <origin rpy="0 0 0" xyz="-0.0545 -0.0325 ${box_len_z}"/>
</joint>
<link name="box_display">
  <visual>
    <origin rpy="0 0 ${pi/2}" xyz="0 0 ${0.0135/2}"/>
    <geometry>
      <box size="0.024 0.047 0.0135"/>
    </geometry>
    <material name="red">
      <color rgba="1 0 0 1"/>
    </material>
  </visual>
</link>

<!-- Lid Handle -->

<joint name="box_lid_opening_pos_1_joint" type="fixed">
  <parent link="box_corner_1"/>
  <child link="box_lid_opening_pos_1"/>
  <origin rpy="${pi} ${pi/2} ${-pi/2}" xyz="0.034 0.044 ${box_len_z}"/>
</joint>
<link name="box_lid_opening_pos_1">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="0.01" length="0.01"/>
    </geometry>
    <material name="green">
      <color rgba="0 1 0 1"/>
    </material>
  </visual>
</link>

<joint name="box_lid_opening_pos_2_joint" type="fixed">
  <parent link="box_corner_1"/>
  <child link="box_lid_opening_pos_2"/>
  <origin rpy="${pi} ${pi/2} ${-pi/2}" xyz="0.0955 0.044 ${box_len_z}"/>
</joint>
<link name="box_lid_opening_pos_2">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="0.01" length="0.01"/>
    </geometry>
    <material name="green">
      <color rgba="0 1 0 1"/>
    </material>
  </visual>
</link>

<joint name="box_lid_opening_pos_3_joint" type="fixed">
  <parent link="box_corner_1"/>
  <child link="box_lid_opening_pos_3"/>
  <origin rpy="${pi} ${pi/2} ${-pi/2}" xyz="0.0955 0.044 ${box_len_z + box_len_z}"/>
</joint>
<link name="box_lid_opening_pos_3">
  <visual>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <geometry>
      <cylinder radius="0.01" length="0.01"/>
    </geometry>
    <material name="green">
      <color rgba="0 1 0 1"/>
    </material>
  </visual>
</link>

</robot>

